#!/bin/bash
A script that generates the assembly code (intel syntax) of a *C* code and save it in an output file. The *C* file name will be saved in the variable *$CFILE*. The output file should be named the same as *C*file, but with the extension *.s* instead od *.c*.
*Example:* if the *C* file is *main.c*, the output file should be *main.s* using *gcc -S -masm=intel $CFILE*.
